### ISSUE TITLE
Incorrect number of seconds in a day

### ISSUE THREAD

**Issue by Pikamander2** [apple/GCGC#12]
Hi there, I used a code search and found an incorrect number of seconds in a day (84600 instead of 86400) listed in one of your files. I recommend fixing it to avoid incorrect timings that could potentially lead to unexpected behavior.

https://github.com/apple/GCGC/blob/fa043adedee735fcccf6b79ceca8f837c0c77b4d/src/filter_and_group.py#L192

**Comment by ivankrylov** [comment]
Thanks for filing an issue. This error is in a comment only, that actual constant is in line 200 and it is correct.
