### ISSUE TITLE
Generational ZGC Support

### ISSUE THREAD

**Issue by DanielThomas** [apple/GCGC#6]
Generational ZGC adds 'Minor' and 'Major' to the label causing the `(?:Garbage Collection)` group not to match:

```
[2022-11-22T04:18:09.618+0000][1583.644s][5085][info ][gc               ] GC(163) Minor Garbage Collection (High Usage) 42238M(95%)->16152M(36%) 0.641s
```

It's also not aware of generations, so the heap filled metrics get confused when a major collection happens. Log attached for convenience:

[GenZGC.log.zip](https://github.com/apple/GCGC/files/10071491/GenZGC.log.zip)

**Comment by ivankrylov** [comment]
I think this was addressed recently with https://github.com/apple/GCGC/commit/9e15caab3ee3f346abb78bf72712df8ed9dabd3d

**Comment by bmathiske** [comment]
Let's close this issue since Gen ZGC support is now implemented. If it does not work as expected, please file another issue!
